version: '3'
services:
  telegraf:
    image: telegraf:1.21.2-alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - "8125:8125"
    networks:
      - teleg

  influxdb:
    image: influxdb:1.8.10-alpine
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - teleg

  grafana:
    image: grafana/grafana:8.3.3
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/ # https://grafana.com/grafana/dashboards/928
    networks:
      - teleg

volumes:
  grafana_data: {}
  influxdb_data: {}

networks:
  teleg:
